AY2122S1-CS2113T-W11-4/tp

docs/AboutUs.md
jianhui has added his details in AboutUs.md
=> add jianhui details

docs/AboutUs.md
Replace Don Joe's name and GitHub link with Renzo's name and GitHub link.
=> Add Renzo's details to AboutUs.md, replacing Don Joe.

docs/AboutUs.md
=> add Rakesh info

src/main/java/seedu/duke/IngredientList.java, src/main/java/seedu/duke/command/Command.java, src/main/java/seedu/duke/command/CommandNames.java
Implement command to List all Ingredients.
=> Implement List Ingredients

src/main/java/seedu/duke/Ingredient.java, src/main/java/seedu/duke/IngredientList.java, src/main/java/seedu/duke/InputParser.java, src/main/java/seedu/duke/command/AddCommand.java
add code to update ingredient class & ingredientLis class
=> update Ingredient class & IngredientList class

src/main/java/seedu/duke/DishList.java, src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/IngredientList.java, src/main/java/seedu/duke/InputParser.java, src/main/java/seedu/duke/command/AddCommand.java, src/main/java/seedu/duke/command/Command.java, src/main/java/seedu/duke/command/CommandNames.java, src/main/java/seedu/duke/command/ListCommand.java, src/main/java/seedu/duke/command/TestCommand.java
Hotfix. Please review as a team once available.
=> Fix bugs to listIngredients that did not allow it to print the list of ingredients

src/main/java/seedu/duke/Ui.java, src/main/java/seedu/duke/command/AddDishIngrCommand.java
Add assertion and logging for both Ui and AddDishIngrCommand class
=> Add assertion and logging for Ui class and AddDishIngrCommand class

src/main/java/seedu/duke/command/AddIngrCommand.java, src/main/java/seedu/duke/command/AddIngrStoredCommand.java, src/main/java/seedu/duke/command/AddIngrWasteCommand.java
Implement logging to AddIngrCommand, AddIngrStoredCommand, AddIngrWasteCommand by jhsee5
=> Implement logging to AddIngrCommand, AddIngrStoredCommand, AddIngrWasteCommand by jhsee5

src/main/java/seedu/foodorama/Ingredient.java, src/main/java/seedu/foodorama/IngredientList.java, src/main/java/seedu/foodorama/InputParser.java, src/main/java/seedu/foodorama/Ui.java, src/main/java/seedu/foodorama/command/CommandNames.java, src/main/java/seedu/foodorama/command/SetIngrExpiryCommand.java, src/main/java/seedu/foodorama/storage/Storage.java
Add ability to set expiry date of ingredients
=> Add ability to set expiry date of ingredients

docs/AboutUs.md
Fix AboutUs.md bug that causes the images to not appear correctly
=> Fix AboutUs.md bug that causes the images to not appear correctly

src/main/java/seedu/foodorama/command/CommandNames.java, src/main/java/seedu/foodorama/command/RandomDishCommand.java
=> Add RandomDishCommand feature

src/main/java/seedu/foodorama/Dish.java, src/main/java/seedu/foodorama/Ingredient.java, src/main/java/seedu/foodorama/Ui.java, src/main/java/seedu/foodorama/command/AddDishCommand.java, src/main/java/seedu/foodorama/command/AddDishWasteCommand.java, src/main/java/seedu/foodorama/command/AddIngrCommand.java, src/main/java/seedu/foodorama/command/AddIngrStoredCommand.java, src/main/java/seedu/foodorama/command/ClearAllCommand.java, src/main/java/seedu/foodorama/command/EditDishCommand.java, src/main/java/seedu/foodorama/command/EditIngrCommand.java, src/main/java/seedu/foodorama/command/FindCommand.java, src/main/java/seedu/foodorama/command/GraphCommand.java, src/main/java/seedu/foodorama/command/HelpCommand.java, src/main/java/seedu/foodorama/command/LinkCommand.java, src/main/java/seedu/foodorama/command/ListCommand.java, src/main/java/seedu/foodorama/command/SetDishLimitCommand.java, src/main/java/seedu/foodorama/command/SetIngrLimitCommand.java, src/main/java/seedu/foodorama/command/SortDishCommand.java, src/main/java/seedu/foodorama/command/SortIngrCommand.java
Fix Renzo code review bugs issued by nishanthelango
=> Fix Renzo code review bugs

docs/UserGuide.md
Fix smaller bugs in UserGuide.md (Issues #134 and #140)
=> Fix smaller bugs in UserGuide.md (Issues #134 and #140)

docs/UserGuide.md
Fix bugs in UserGuide.md (issues #135, #136, #137)
=> Fix bugs in UserGuide.md (issues #135, #136, #137)

src/main/java/seedu/foodorama/Dish.java, src/main/java/seedu/foodorama/DishList.java, src/main/java/seedu/foodorama/Ingredient.java, src/main/java/seedu/foodorama/IngredientList.java, src/main/java/seedu/foodorama/InputParser.java, src/main/java/seedu/foodorama/Ui.java, src/main/java/seedu/foodorama/command/CommandNames.java, src/main/java/seedu/foodorama/command/EditDishNameCommand.java, src/main/java/seedu/foodorama/command/EditDishWasteCommand.java, src/main/java/seedu/foodorama/command/EditIngrNameCommand.java, src/main/java/seedu/foodorama/command/EditIngrStoredCommand.java, src/main/java/seedu/foodorama/command/EditIngrWasteCommand.java, src/test/java/seedu/foodorama/command/EditDishNameCommandTest.java, src/test/java/seedu/foodorama/command/EditIngrNameCommandTest.java
Add Edit commands for wastage and storage
=> Add Edit commands for wastage and storage

docs/UserGuide.md
Update UserGuide.md with new edit commands and reformat icon style
=> Update UserGuide.md with new edit commands and reformat icon style

src/main/java/seedu/foodorama/IngredientList.java, src/main/java/seedu/foodorama/InputParser.java, src/main/java/seedu/foodorama/Ui.java, src/main/java/seedu/foodorama/command/CommandNames.java
Fix bug in edit command that used the wrong formatting for command name
=> Fix bug in edit command that used the wrong formatting for command name

src/main/java/seedu/foodorama/Ui.java, src/main/java/seedu/foodorama/command/RandomDishCommand.java, src/test/java/seedu/foodorama/command/RandomDishCommandTest.java, src/test/java/seedu/foodorama/command/SortDishCommandTest.java, text-ui-test/data/formats.txt, text-ui-test/log/programLog.log
add JUnit5 test for RandomDishCommand, RandomDishCommandTest
=> add JUnit5 test for RandomDishCommand, RandomDishCommandTest

src/main/java/seedu/foodorama/Ingredient.java, src/test/java/seedu/foodorama/command/SetIngrExpiryCommandTest.java
Add JUnit test for 'set ingr expiry' command
=> Add JUnit test for 'set ingr expiry' command

docs/team/Rakesh12000.md, docs/team/jhsee5.md, docs/team/johndoe.md, docs/team/renzocanare.md
=> add PPP templates for team

docs/team/Rakesh12000.md, docs/team/dniv-ra.md, docs/team/jhsee5.md, docs/team/renzocanare.md
standardized Arvind's PPP template
=> more template content

docs/team/jhsee5.md
=> jhsee5 PPP draft

docs/UserGuide.md
=> Add rdish to UG

docs/team/dniv-ra.md, docs/team/jhsee5.md, docs/team/rakesh12000.md, docs/team/renzocanare.md
edit all .md to lowercase and RepoSense spelling
=> new line to all PPP

docs/team/renzocanare.md
Add renzocanare.md information
=> Add renzocanare.md information

docs/team/renzocanare.md
=> Update PPP for renzocanare.md

src/main/java/seedu/foodorama/IngredientList.java, src/main/java/seedu/foodorama/Ui.java
Update bug on SetIngrExpiry that causes it to not loop properly, add confirmation on far expiry dates
=> Update bug on SetIngrExpiry that causes it to not loop properly, add confirmation on far expiry dates

src/main/java/seedu/foodorama/command/FindCommand.java
Fix command trim bug on FindCommand
=> Fix command trim bug on FindCommand

docs/UserGuide.md
Update UG with changes to Find Command
=> Update UG with changes to Find Command

src/main/java/seedu/foodorama/Dish.java, src/main/java/seedu/foodorama/Ingredient.java, src/main/java/seedu/foodorama/IngredientList.java, src/main/java/seedu/foodorama/Ui.java
=> Branch loop weights

src/main/java/seedu/foodorama/Dish.java
=> fix add dish waste

src/main/java/seedu/foodorama/Dish.java, src/main/java/seedu/foodorama/Ui.java
standardise UI for weight loops
=> standardise UI for weight loops

src/main/java/seedu/foodorama/Ui.java
update UI for add ingr and add dish name being a number
=> update UI for add ingr and add dish name being a number

src/main/java/seedu/foodorama/Dish.java, src/main/java/seedu/foodorama/Ingredient.java, src/main/java/seedu/foodorama/Ui.java
Fix Ui Inconsistencies and bugs
=> Fix Ui Inconsistencies and bugs

src/main/java/seedu/foodorama/ClearScreen.java, src/main/java/seedu/foodorama/DishList.java, src/main/java/seedu/foodorama/Ui.java, src/main/java/seedu/foodorama/command/AddDishCommand.java, src/main/java/seedu/foodorama/command/AddDishWasteCommand.java, src/main/java/seedu/foodorama/command/AddIngrCommand.java, src/main/java/seedu/foodorama/command/AddIngrStoredCommand.java, src/main/java/seedu/foodorama/command/AddIngrWasteCommand.java, src/main/java/seedu/foodorama/command/ClearAllCommand.java, src/main/java/seedu/foodorama/command/ClearDishCommand.java
Update JavaDoc for classes/methods tasked to Renzo
=> Update JavaDoc for classes/methods tasked to Renzo

src/main/java/seedu/foodorama/Ui.java
=> Format Ui messages

docs/UserGuide.md
Update UserGuide.md with new outputs
=> Update UserGuide.md with new outputs

src/main/java/seedu/foodorama/Foodorama.java, src/main/java/seedu/foodorama/Ingredient.java, src/main/java/seedu/foodorama/command/ListCommand.java, src/main/java/seedu/foodorama/command/RandomDishCommand.java, src/main/java/seedu/foodorama/command/SetDishLimitCommand.java, src/main/java/seedu/foodorama/command/SetIngrExpiryCommand.java, src/main/java/seedu/foodorama/command/SetIngrLimitCommand.java, src/main/java/seedu/foodorama/command/SortDishCommand.java, src/main/java/seedu/foodorama/command/SortIngrCommand.java
=> Branch jhsee5 java doc

docs/UserGuide.md, src/main/java/seedu/foodorama/Ui.java
Add Format Notes to UserGuide.md, adjust Ui Class message outputs
=> Add Format Notes to UserGuide.md, adjust Ui Class message outputs

docs/DeveloperGuide.md
Finalize manual testing section in DG
=> Finalize manual testing section in DG

src/main/java/seedu/foodorama/Dish.java, src/main/java/seedu/foodorama/DishList.java, src/main/java/seedu/foodorama/Ingredient.java, src/main/java/seedu/foodorama/IngredientList.java, src/main/java/seedu/foodorama/InputParser.java, src/main/java/seedu/foodorama/Ui.java, src/main/java/seedu/foodorama/command/AddDishCommand.java, src/main/java/seedu/foodorama/command/AddDishWasteCommand.java, src/main/java/seedu/foodorama/command/AddIngrCommand.java, src/main/java/seedu/foodorama/command/AddIngrStoredCommand.java, src/main/java/seedu/foodorama/command/AddIngrWasteCommand.java, src/main/java/seedu/foodorama/command/ClearAllCommand.java, src/main/java/seedu/foodorama/command/DeleteDishCommand.java, src/main/java/seedu/foodorama/command/DeleteIngrCommand.java, src/main/java/seedu/foodorama/command/EditDishNameCommand.java, src/main/java/seedu/foodorama/command/EditDishWasteCommand.java, src/main/java/seedu/foodorama/command/EditIngrNameCommand.java, src/main/java/seedu/foodorama/command/EditIngrStoredCommand.java, src/main/java/seedu/foodorama/command/EditIngrWasteCommand.java, src/main/java/seedu/foodorama/command/FindCommand.java, src/main/java/seedu/foodorama/command/GraphCommand.java, src/main/java/seedu/foodorama/command/LinkCommand.java, src/main/java/seedu/foodorama/command/ListCommand.java, src/main/java/seedu/foodorama/command/SetDishLimitCommand.java, src/main/java/seedu/foodorama/command/SetIngrExpiryCommand.java, src/main/java/seedu/foodorama/command/SetIngrLimitCommand.java, src/main/java/seedu/foodorama/storage/Storage.java, src/test/java/seedu/foodorama/command/FindCommandTest.java
Remove Magic Literals, left maf
=> Remove Magic Literals

docs/team/renzocanare.md
=> Update renzocanare.md PPP

docs/team/jhsee5.md
=> jhsee5 PPP

docs/team/renzocanare.md
=> Finalize renzocanare.md PPP

docs/team/renzocanare.md
Finalize PPP formatting renzocanare.md
=> Finalize PPP formatting renzocanare.md
